export const currentCurrencyList = [
    {
        "result": 1,
        "cur_unit": "AED",
        "ttb": "358.05",
        "tts": "365.28",
        "deal_bas_r": "361.67",
        "bkpr": "361",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "361",
        "kftc_deal_bas_r": "361.67",
        "cur_nm": "아랍에미리트 디르함"
    },
    {
        "result": 1,
        "cur_unit": "AUD",
        "ttb": "897.1",
        "tts": "915.23",
        "deal_bas_r": "906.17",
        "bkpr": "906",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "906",
        "kftc_deal_bas_r": "906.17",
        "cur_nm": "호주 달러"
    },
    {
        "result": 1,
        "cur_unit": "BHD",
        "ttb": "3,488.46",
        "tts": "3,558.93",
        "deal_bas_r": "3,523.7",
        "bkpr": "3,523",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "3,523",
        "kftc_deal_bas_r": "3,523.7",
        "cur_nm": "바레인 디나르"
    },
    {
        "result": 1,
        "cur_unit": "BND",
        "ttb": "1,019.78",
        "tts": "1,040.39",
        "deal_bas_r": "1,030.09",
        "bkpr": "1,030",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "1,030",
        "kftc_deal_bas_r": "1,030.09",
        "cur_nm": "브루나이 달러"
    },
    {
        "result": 1,
        "cur_unit": "CAD",
        "ttb": "975.13",
        "tts": "994.82",
        "deal_bas_r": "984.98",
        "bkpr": "984",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "984",
        "kftc_deal_bas_r": "984.98",
        "cur_nm": "캐나다 달러"
    },
    {
        "result": 1,
        "cur_unit": "CHF",
        "ttb": "1,546.38",
        "tts": "1,577.62",
        "deal_bas_r": "1,562",
        "bkpr": "1,562",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "1,562",
        "kftc_deal_bas_r": "1,562",
        "cur_nm": "스위스 프랑"
    },
    {
        "result": 1,
        "cur_unit": "CNH",
        "ttb": "187.58",
        "tts": "191.37",
        "deal_bas_r": "189.48",
        "bkpr": "189",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "189",
        "kftc_deal_bas_r": "189.48",
        "cur_nm": "위안화"
    },
    {
        "result": 1,
        "cur_unit": "DKK",
        "ttb": "196.26",
        "tts": "200.23",
        "deal_bas_r": "198.25",
        "bkpr": "198",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "198",
        "kftc_deal_bas_r": "198.25",
        "cur_nm": "덴마아크 크로네"
    },
    {
        "result": 1,
        "cur_unit": "EUR",
        "ttb": "1,463.92",
        "tts": "1,493.49",
        "deal_bas_r": "1,478.71",
        "bkpr": "1,478",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "1,478",
        "kftc_deal_bas_r": "1,478.71",
        "cur_nm": "유로"
    },
    {
        "result": 1,
        "cur_unit": "GBP",
        "ttb": "1,751.66",
        "tts": "1,787.05",
        "deal_bas_r": "1,769.36",
        "bkpr": "1,769",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "1,769",
        "kftc_deal_bas_r": "1,769.36",
        "cur_nm": "영국 파운드"
    },
    {
        "result": 1,
        "cur_unit": "HKD",
        "ttb": "168.92",
        "tts": "172.33",
        "deal_bas_r": "170.63",
        "bkpr": "170",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "170",
        "kftc_deal_bas_r": "170.63",
        "cur_nm": "홍콩 달러"
    },
    {
        "result": 1,
        "cur_unit": "IDR(100)",
        "ttb": "8.71",
        "tts": "8.88",
        "deal_bas_r": "8.8",
        "bkpr": "8",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "8",
        "kftc_deal_bas_r": "8.8",
        "cur_nm": "인도네시아 루피아"
    },
    {
        "result": 1,
        "cur_unit": "JPY(100)",
        "ttb": "908.82",
        "tts": "927.19",
        "deal_bas_r": "918.01",
        "bkpr": "918",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "918",
        "kftc_deal_bas_r": "918.01",
        "cur_nm": "일본 옌"
    },
    {
        "result": 1,
        "cur_unit": "KRW",
        "ttb": "0",
        "tts": "0",
        "deal_bas_r": "1",
        "bkpr": "1",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "1",
        "kftc_deal_bas_r": "1",
        "cur_nm": "한국 원"
    },
    {
        "result": 1,
        "cur_unit": "KWD",
        "ttb": "4,306.21",
        "tts": "4,393.2",
        "deal_bas_r": "4,349.71",
        "bkpr": "4,349",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "4,349",
        "kftc_deal_bas_r": "4,349.71",
        "cur_nm": "쿠웨이트 디나르"
    },
    {
        "result": 1,
        "cur_unit": "MYR",
        "ttb": "318.35",
        "tts": "324.78",
        "deal_bas_r": "321.57",
        "bkpr": "321",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "321",
        "kftc_deal_bas_r": "321.57",
        "cur_nm": "말레이지아 링기트"
    },
    {
        "result": 1,
        "cur_unit": "NOK",
        "ttb": "124.34",
        "tts": "126.85",
        "deal_bas_r": "125.6",
        "bkpr": "125",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "125",
        "kftc_deal_bas_r": "125.6",
        "cur_nm": "노르웨이 크로네"
    },
    {
        "result": 1,
        "cur_unit": "NZD",
        "ttb": "823.19",
        "tts": "839.82",
        "deal_bas_r": "831.51",
        "bkpr": "831",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "831",
        "kftc_deal_bas_r": "831.51",
        "cur_nm": "뉴질랜드 달러"
    },
    {
        "result": 1,
        "cur_unit": "SAR",
        "ttb": "350.51",
        "tts": "357.6",
        "deal_bas_r": "354.06",
        "bkpr": "354",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "354",
        "kftc_deal_bas_r": "354.06",
        "cur_nm": "사우디 리얄"
    },
    {
        "result": 1,
        "cur_unit": "SEK",
        "ttb": "129.05",
        "tts": "131.66",
        "deal_bas_r": "130.36",
        "bkpr": "130",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "130",
        "kftc_deal_bas_r": "130.36",
        "cur_nm": "스웨덴 크로나"
    },
    {
        "result": 1,
        "cur_unit": "SGD",
        "ttb": "1,019.78",
        "tts": "1,040.39",
        "deal_bas_r": "1,030.09",
        "bkpr": "1,030",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "1,030",
        "kftc_deal_bas_r": "1,030.09",
        "cur_nm": "싱가포르 달러"
    },
    {
        "result": 1,
        "cur_unit": "THB",
        "ttb": "40.19",
        "tts": "41",
        "deal_bas_r": "40.6",
        "bkpr": "40",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "40",
        "kftc_deal_bas_r": "40.6",
        "cur_nm": "태국 바트"
    },
    {
        "result": 1,
        "cur_unit": "USD",
        "ttb": "1,315.11",
        "tts": "1,341.68",
        "deal_bas_r": "1,328.4",
        "bkpr": "1,328",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "1,328",
        "kftc_deal_bas_r": "1,328.4",
        "cur_nm": "미국 달러"
    }
]