export const currentCurrencyList = [
    {
        "result": 1,
        "cur_unit": "AED",
        "ttb": "363.49",
        "tts": "370.84",
        "deal_bas_r": "367.17",
        "bkpr": "367",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "367",
        "kftc_deal_bas_r": "367.17",
        "cur_nm": "아랍에미리트 디르함"
    },
    {
        "result": 1,
        "cur_unit": "AUD",
        "ttb": "899.66",
        "tts": "917.83",
        "deal_bas_r": "908.75",
        "bkpr": "908",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "908",
        "kftc_deal_bas_r": "908.75",
        "cur_nm": "호주 달러"
    },
    {
        "result": 1,
        "cur_unit": "BHD",
        "ttb": "3,541.31",
        "tts": "3,612.86",
        "deal_bas_r": "3,577.09",
        "bkpr": "3,577",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "3,577",
        "kftc_deal_bas_r": "3,577.09",
        "cur_nm": "바레인 디나르"
    },
    {
        "result": 1,
        "cur_unit": "BND",
        "ttb": "1,021.85",
        "tts": "1,042.5",
        "deal_bas_r": "1,032.18",
        "bkpr": "1,032",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "1,032",
        "kftc_deal_bas_r": "1,032.18",
        "cur_nm": "브루나이 달러"
    },
    {
        "result": 1,
        "cur_unit": "CAD",
        "ttb": "968.98",
        "tts": "988.55",
        "deal_bas_r": "978.77",
        "bkpr": "978",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "978",
        "kftc_deal_bas_r": "978.77",
        "cur_nm": "캐나다 달러"
    },
    {
        "result": 1,
        "cur_unit": "CHF",
        "ttb": "1,556.26",
        "tts": "1,587.69",
        "deal_bas_r": "1,571.98",
        "bkpr": "1,571",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "1,571",
        "kftc_deal_bas_r": "1,571.98",
        "cur_nm": "스위스 프랑"
    },
    {
        "result": 1,
        "cur_unit": "CNH",
        "ttb": "188.39",
        "tts": "192.2",
        "deal_bas_r": "190.3",
        "bkpr": "190",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "190",
        "kftc_deal_bas_r": "190.3",
        "cur_nm": "위안화"
    },
    {
        "result": 1,
        "cur_unit": "DKK",
        "ttb": "195.56",
        "tts": "199.51",
        "deal_bas_r": "197.54",
        "bkpr": "197",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "197",
        "kftc_deal_bas_r": "197.54",
        "cur_nm": "덴마아크 크로네"
    },
    {
        "result": 1,
        "cur_unit": "EUR",
        "ttb": "1,459.01",
        "tts": "1,488.48",
        "deal_bas_r": "1,473.75",
        "bkpr": "1,473",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "1,473",
        "kftc_deal_bas_r": "1,473.75",
        "cur_nm": "유로"
    },
    {
        "result": 1,
        "cur_unit": "GBP",
        "ttb": "1,742.79",
        "tts": "1,778",
        "deal_bas_r": "1,760.4",
        "bkpr": "1,760",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "1,760",
        "kftc_deal_bas_r": "1,760.4",
        "cur_nm": "영국 파운드"
    },
    {
        "result": 1,
        "cur_unit": "HKD",
        "ttb": "171.83",
        "tts": "175.3",
        "deal_bas_r": "173.57",
        "bkpr": "173",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "173",
        "kftc_deal_bas_r": "173.57",
        "cur_nm": "홍콩 달러"
    },
    {
        "result": 1,
        "cur_unit": "IDR(100)",
        "ttb": "8.57",
        "tts": "8.74",
        "deal_bas_r": "8.66",
        "bkpr": "8",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "8",
        "kftc_deal_bas_r": "8.66",
        "cur_nm": "인도네시아 루피아"
    },
    {
        "result": 1,
        "cur_unit": "JPY(100)",
        "ttb": "894.27",
        "tts": "912.34",
        "deal_bas_r": "903.31",
        "bkpr": "903",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "903",
        "kftc_deal_bas_r": "903.31",
        "cur_nm": "일본 옌"
    },
    {
        "result": 1,
        "cur_unit": "KRW",
        "ttb": "0",
        "tts": "0",
        "deal_bas_r": "1",
        "bkpr": "1",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "1",
        "kftc_deal_bas_r": "1",
        "cur_nm": "한국 원"
    },
    {
        "result": 1,
        "cur_unit": "KWD",
        "ttb": "4,354.43",
        "tts": "4,442.4",
        "deal_bas_r": "4,398.42",
        "bkpr": "4,398",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "4,398",
        "kftc_deal_bas_r": "4,398.42",
        "cur_nm": "쿠웨이트 디나르"
    },
    {
        "result": 1,
        "cur_unit": "MYR",
        "ttb": "311.39",
        "tts": "317.68",
        "deal_bas_r": "314.54",
        "bkpr": "314",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "314",
        "kftc_deal_bas_r": "314.54",
        "cur_nm": "말레이지아 링기트"
    },
    {
        "result": 1,
        "cur_unit": "NOK",
        "ttb": "124.48",
        "tts": "126.99",
        "deal_bas_r": "125.74",
        "bkpr": "125",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "125",
        "kftc_deal_bas_r": "125.74",
        "cur_nm": "노르웨이 크로네"
    },
    {
        "result": 1,
        "cur_unit": "NZD",
        "ttb": "814.01",
        "tts": "830.46",
        "deal_bas_r": "822.24",
        "bkpr": "822",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "822",
        "kftc_deal_bas_r": "822.24",
        "cur_nm": "뉴질랜드 달러"
    },
    {
        "result": 1,
        "cur_unit": "SAR",
        "ttb": "355.57",
        "tts": "362.76",
        "deal_bas_r": "359.17",
        "bkpr": "359",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "359",
        "kftc_deal_bas_r": "359.17",
        "cur_nm": "사우디 리얄"
    },
    {
        "result": 1,
        "cur_unit": "SEK",
        "ttb": "128.52",
        "tts": "131.11",
        "deal_bas_r": "129.82",
        "bkpr": "129",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "129",
        "kftc_deal_bas_r": "129.82",
        "cur_nm": "스웨덴 크로나"
    },
    {
        "result": 1,
        "cur_unit": "SGD",
        "ttb": "1,021.85",
        "tts": "1,042.5",
        "deal_bas_r": "1,032.18",
        "bkpr": "1,032",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "1,032",
        "kftc_deal_bas_r": "1,032.18",
        "cur_nm": "싱가포르 달러"
    },
    {
        "result": 1,
        "cur_unit": "THB",
        "ttb": "40.21",
        "tts": "41.02",
        "deal_bas_r": "40.62",
        "bkpr": "40",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "40",
        "kftc_deal_bas_r": "40.62",
        "cur_nm": "태국 바트"
    },
    {
        "result": 1,
        "cur_unit": "USD",
        "ttb": "1,335.11",
        "tts": "1,362.08",
        "deal_bas_r": "1,348.6",
        "bkpr": "1,348",
        "yy_efee_r": "0",
        "ten_dd_efee_r": "0",
        "kftc_bkpr": "1,348",
        "kftc_deal_bas_r": "1,348.6",
        "cur_nm": "미국 달러"
    }
]